Repository googleapis/java-game-servers, pull requests merged in 2020-06, with the labels that each got.

#140 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#142 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#144 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#146 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#151 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#155 ci: switch to secret manager for sample/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#159 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  .gitignore
  google-cloud-gameservices/pom.xml
  grpc-google-cloud-gameservices-v1alpha/pom.xml
  pom.xml
  proto-google-cloud-gameservices-v1alpha/pom.xml
Labels: cla: yes

#160 chore: update README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#169 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none
