Repository googleapis/java-game-servers, pull requests merged in 2020-10, with the labels that each got.

#225 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: api: gameservices, automerge, cla: yes, context: full

#226 build(java): readme.sh should be executable
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#241 ci(java): restrict presubmit samples ITs to only snapshot
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#242 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#243 build(java): auto-approve README regeneration
  .github/workflows/approve-readme.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#244 build(java): enable snippet-bot
  .github/snippet-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full

#245 chore: clean up and update renovate.json
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#254 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#255 chore: regenerate common templates
  .kokoro/release/publish_javadoc.sh
  CODE_OF_CONDUCT.md
  synth.metadata
Labels: api: gameservices, automerge, cla: yes, context: full

#257 chore(ci): fix typo in restrict presubmit samples ITs to only snapshot
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#229 feat: promote to 1.0.0
  .repo-metadata.json
Labels: api: gameservices, cla: yes

#260 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#263 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#264 chore(java): enable generated-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full
