Repository googleapis/java-game-servers, pull requests merged in 2020-07, with the labels that each got.

#178 chore: rename repo to match other languages
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/PULL_REQUEST_TEMPLATE.md
  .kokoro/build.sh
  .kokoro/common.cfg
  .kokoro/continuous/common.cfg
  .kokoro/continuous/dependencies.cfg
  .kokoro/continuous/java8-osx.cfg
  .kokoro/continuous/java8-win.cfg
  .kokoro/continuous/propose_release.cfg
  .kokoro/nightly/common.cfg
  .kokoro/nightly/dependencies.cfg
  .kokoro/nightly/java8-osx.cfg
  .kokoro/nightly/java8-win.cfg
  .kokoro/presubmit/common.cfg
  .kokoro/presubmit/dependencies.cfg
  .kokoro/presubmit/java8-osx.cfg
  .kokoro/presubmit/java8-win.cfg
  .kokoro/presubmit/linkage-monitor.cfg
  .kokoro/release/bump_snapshot.cfg
  .kokoro/release/common.cfg
  .kokoro/release/drop.cfg
  .kokoro/release/promote.cfg
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/snapshot.cfg
  .kokoro/release/stage.cfg
  .repo-metadata.json
  README.md
  pom.xml
  renovate.json
  synth.metadata
Labels: automerge, cla: yes

#180 chore: mark client as beta
  .repo-metadata.json
  README.md
Labels: cla: yes

#179 samples: clean up samples pom.xml files
  samples/install-without-bom/pom.xml
  samples/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
Labels: cla: yes

#186 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#187 chore(docs): add cloud-RAD
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: automerge, cla: yes, context: full
