Repository googleapis/java-game-servers, pull requests merged in 2020-09, with the labels that each got.

#207 chore: regenerate README
  .kokoro/nightly/integration.cfg
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  README.md
  synth.metadata
Labels: api: gameservices, cla: yes, context: none

#211 chore: regenerate templates
  .github/CODEOWNERS
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#220 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#222 build(java): use yoshi-approver token for auto-approve
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#221 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: gameservices, automerge, cla: yes

#224 chore: regenerate templates
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full
