Repository googleapis/java-game-servers, pull requests merged in 2020-08, with the labels that each got.

#189 cleanup: removes unused kokoro config files
  .kokoro/continuous/dependencies.cfg
  .kokoro/continuous/integration.cfg
  .kokoro/continuous/java11.cfg
  .kokoro/continuous/java7.cfg
  .kokoro/continuous/java8-osx.cfg
  .kokoro/continuous/java8-win.cfg
  .kokoro/continuous/lint.cfg
  .kokoro/continuous/propose_release.cfg
  .kokoro/continuous/samples.cfg
  .kokoro/nightly/dependencies.cfg
  .kokoro/nightly/lint.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#196 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#200 test: add integration test for v1
  google-cloud-game-servers/pom.xml
  google-cloud-game-servers/src/test/java/com/google/cloud/gaming/v1/it/ITSystemTest.java
Labels: cla: yes

#201 samples: add presubmit lint check
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#202 build: temporarily disable reporting to unblock releases
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: gameservices, cla: yes, context: full

#203 build(java): switch to release-publish app for notifying GitHub of release status
  .kokoro/release/stage.cfg
  .kokoro/release/stage.sh
  synth.metadata
Labels: cla: yes, context: full

#73 samples: migrate samples from java-docs-samples
  .kokoro/nightly/integration.cfg
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  pom.xml
  samples/install-without-bom/pom.xml
  samples/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
  samples/snippets/src/main/java/com/example/gameservices/clusters/CreateCluster.java
  samples/snippets/src/main/java/com/example/gameservices/clusters/DeleteCluster.java
  samples/snippets/src/main/java/com/example/gameservices/clusters/GetCluster.java
  samples/snippets/src/main/java/com/example/gameservices/clusters/ListClusters.java
  samples/snippets/src/main/java/com/example/gameservices/clusters/UpdateCluster.java
  samples/snippets/src/main/java/com/example/gameservices/deployments/CreateDeployment.java
  samples/snippets/src/main/java/com/example/gameservices/deployments/DeleteDeployment.java
  samples/snippets/src/main/java/com/example/gameservices/deployments/GetDeployment.java
  samples/snippets/src/main/java/com/example/gameservices/deployments/ListDeployments.java
  samples/snippets/src/main/java/com/example/gameservices/deployments/UpdateDeployment.java
  samples/snippets/src/main/java/com/example/gameservices/realms/CreateRealm.java
  samples/snippets/src/main/java/com/example/gameservices/realms/DeleteRealm.java
  samples/snippets/src/main/java/com/example/gameservices/realms/GetRealm.java
  samples/snippets/src/main/java/com/example/gameservices/realms/ListRealms.java
  samples/snippets/src/main/java/com/example/gameservices/realms/UpdateRealm.java
  samples/snippets/src/test/java/com/example/gameservices/ClusterTests.java
  samples/snippets/src/test/java/com/example/gameservices/DeploymentTests.java
  samples/snippets/src/test/java/com/example/gameservices/GameServicesTestUtil.java
  samples/snippets/src/test/java/com/example/gameservices/RealmTests.java
Labels: api: gameservices, cla: yes
