Repository googleapis/java-game-servers, pull requests merged in 2021-05, with the labels that each got.

#421 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: gameservices, automerge, cla: yes, context: none

#422 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: gameservices, automerge, cla: yes

#423 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: gameservices, automerge, cla: yes, context: full

#432 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: gameservices, automerge, cla: yes

#431 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: gameservices, automerge, cla: yes, context: full

#433 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: gameservices, automerge, cla: yes, context: full

#435 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: gameservices, automerge, cla: yes, context: full

#438 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: gameservices, automerge, cla: yes, context: full
