Repository googleapis/java-game-servers, pull requests merged in 2021-02, with the labels that each got.

#330 build: migrate to flakybot
  .kokoro/build.sh
Labels: api: gameservices, cla: yes

#333 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: gameservices, automerge, cla: yes

#354 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: gameservices, automerge, cla: yes

#352 test: fix tests to allow running in parallel
  google-cloud-game-servers/src/test/java/com/google/cloud/gaming/v1/it/ITSystemTest.java
  samples/snippets/src/test/java/com/example/gameservices/ClusterTests.java
  samples/snippets/src/test/java/com/example/gameservices/DeploymentTests.java
  samples/snippets/src/test/java/com/example/gameservices/GameServicesTestUtil.java
  samples/snippets/src/test/java/com/example/gameservices/RealmTests.java
Labels: api: gameservices, automerge, cla: yes

#355 docs: generate sample code in the javadocs
  google-cloud-game-servers/src/main/java/com/google/cloud/gaming/v1/GameServerClustersServiceClient.java
  google-cloud-game-servers/src/main/java/com/google/cloud/gaming/v1/GameServerConfigsServiceClient.java
  google-cloud-game-servers/src/main/java/com/google/cloud/gaming/v1/GameServerDeploymentsServiceClient.java
  google-cloud-game-servers/src/main/java/com/google/cloud/gaming/v1/RealmsServiceClient.java
  google-cloud-game-servers/src/main/java/com/google/cloud/gaming/v1/package-info.java
  google-cloud-game-servers/src/main/java/com/google/cloud/gaming/v1/stub/GrpcGameServerClustersServiceStub.java
  google-cloud-game-servers/src/main/java/com/google/cloud/gaming/v1/stub/GrpcGameServerConfigsServiceStub.java
  google-cloud-game-servers/src/main/java/com/google/cloud/gaming/v1/stub/GrpcGameServerDeploymentsServiceStub.java
  google-cloud-game-servers/src/main/java/com/google/cloud/gaming/v1/stub/GrpcRealmsServiceStub.java
  google-cloud-game-servers/src/main/java/com/google/cloud/gaming/v1beta/GameServerClustersServiceClient.java
  google-cloud-game-servers/src/main/java/com/google/cloud/gaming/v1beta/GameServerConfigsServiceClient.java
  google-cloud-game-servers/src/main/java/com/google/cloud/gaming/v1beta/GameServerDeploymentsServiceClient.java
  google-cloud-game-servers/src/main/java/com/google/cloud/gaming/v1beta/RealmsServiceClient.java
  google-cloud-game-servers/src/main/java/com/google/cloud/gaming/v1beta/package-info.java
  google-cloud-game-servers/src/main/java/com/google/cloud/gaming/v1beta/stub/GrpcGameServerClustersServiceStub.java
  google-cloud-game-servers/src/main/java/com/google/cloud/gaming/v1beta/stub/GrpcGameServerConfigsServiceStub.java
  google-cloud-game-servers/src/main/java/com/google/cloud/gaming/v1beta/stub/GrpcGameServerDeploymentsServiceStub.java
  google-cloud-game-servers/src/main/java/com/google/cloud/gaming/v1beta/stub/GrpcRealmsServiceStub.java
  google-cloud-game-servers/src/test/java/com/google/cloud/gaming/v1/MockGameServerClustersServiceImpl.java
  google-cloud-game-servers/src/test/java/com/google/cloud/gaming/v1/MockGameServerConfigsServiceImpl.java
  google-cloud-game-servers/src/test/java/com/google/cloud/gaming/v1/MockGameServerDeploymentsServiceImpl.java
  google-cloud-game-servers/src/test/java/com/google/cloud/gaming/v1/MockRealmsServiceImpl.java
  google-cloud-game-servers/src/test/java/com/google/cloud/gaming/v1beta/MockGameServerClustersServiceImpl.java
  google-cloud-game-servers/src/test/java/com/google/cloud/gaming/v1beta/MockGameServerConfigsServiceImpl.java
  google-cloud-game-servers/src/test/java/com/google/cloud/gaming/v1beta/MockGameServerDeploymentsServiceImpl.java
  google-cloud-game-servers/src/test/java/com/google/cloud/gaming/v1beta/MockRealmsServiceImpl.java
  synth.metadata
Labels: api: gameservices, cla: yes, context: full

#357 chore: regenerate common templates
  .kokoro/build.sh
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: gameservices, automerge, cla: yes, context: full

#364 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: gameservices, automerge, cla: yes
